var templateCell = '<div class="o-feature-content"> '
    + '<div class="o-feature-left">'
    + '<h3 class="o-feature-brand">{{primaryTitle}}</h3>'
    + '<h2 class="o-feature-title"> '
    + '{{secondaryTitle}} ' + '</h2> '
    + '<div class="o-feature-description-inst">'
    + '</div>'
    + '<p>'
    + '{{description}}'
    + '</p>'
    + '<div class="o-feature-description-stud">'
    + '</div>'
    + '<p>'
    + '{{studentDescription}}'
    + '</p>'
    + '{{#hasCTA}}<div class="o-feature-button clearfix"> '
    + '<a aria-label=\"{{secondaryTitle}}\" class=\"o-feature-action-button\" href="{{ctaUrl}}" target="_blank"><div>{{ctaText}}<\/div></a> '
    + '</div>{{/hasCTA}}</div> '
    + '<div class="o-feature-right">'
    + '{{#hasImage}}'
    + '<img class="o-feature-img" width="160" height="160" src="{{resourceUrl}}" alt="{{secondaryTitle}}">'
    + '{{/hasImage}}'
  	+ '</div>'
	  + '</div>'
    + '<div class="o-feature-clearfix"></div>'
    + '<!--New Discipline Feature & Exchange Mobile App UX Component -->'
    + '<div class="o-feature-mobile {{displayMobileFeature}}">'
    + '<div class="o-feature-mobile-left">'
    + '<img class="o-feature-tab" src="../../../images/tab.jpg" width="130"/>'
    + '<img class="o-feature-app-store" src="../../../images/app-store.png" width="100"/>'
    + '<img class="o-feature-g-play" src="../../../images/google-play.png" width="100"/>'
    + '</div>'
    + '<div class="o-feature-mobile-right">'
    + '<div class="o-feature-brand" contenteditable="">{{primaryTitle}}</div>'
    + '<header class="o-feature-title" contenteditable="">{{secondaryTitle}}</header>'
    + '<label class="o-instructor-description-label">Instructor Description</label>'
    + '<div class="o-instructor-description" contenteditable="">{{instructorDescription}}</div>'
    + '<label class="o-student-description-label">Student Description</label>'
    + '<div class="o-student-description" contenteditable="">{{studentDescription}}</div>'
    + '<label>iTunes Download URL</label>'
    + '<div class="o-itunes-download-url" contenteditable="">{{iTunesDownloadUrl}}</div>'
    + '<label>Android Download URL</label>'
    + '<div class="o-android-download-url" contenteditable="">{{androidDownloadUrl}}</div>'
    + '</div>'
    + '</div>'
    + '<div class="o-feature-clearfix"></div>'

module.exports = templateCell;
