var templateCell = '<div class="o-feature-content"> '
    + '<div class="o-feature-left">'
    + '<h3 class="o-feature-brand">{{primaryTitle}}</h3>'
    + '<h2 class="o-feature-title"> '
    + '{{secondaryTitle}} ' + '</h2> '
    + '<div class="o-feature-description-inst">'
    + '</div>'
    + '<p>'
    + '{{description}}'
    + '</p>'
    + '<div class="o-feature-description-stud">'
    + '</div>'
    + '<p>'
    + '{{studentDescription}}'
    + '</p>'
    + '{{#hasCTA}}<div class="o-feature-button clearfix"> '
    + '<a aria-label=\"{{secondaryTitle}}\" class=\"o-feature-action-button\" href="{{ctaUrl}}" target="_blank"><div>{{ctaText}}<\/div></a> '
    + '</div>{{/hasCTA}}</div> '
    + '<div class="o-feature-right">'
    + '{{#hasImage}}'
    + '<img class="o-feature-img" width="160" height="160" src="{{resourceUrl}}" alt="{{secondaryTitle}}">'
    + '{{/hasImage}}'
    + '</div>'
    + '</div>'
    + '<div class="o-feature-clearfix"></div>';
module.exports = templateCell;

