language: node_js
sudo: false
node_js:
- stable
- 4.2
script:
- npm run ci
deploy:
  provider: npm
  email: pearson-design-accelerator@pearson.com
  api_key:
    secure: M3W1K/OjP9hXDYCF8/fHZxZ7qMCriI8K/xC8epxfrxzmNVm5WBPl2J9PYeDu7fpgVKqDpSK0/vaUVnk3IX50xaVwfLVQsRPMB4IV4CAzeHmEF2lqBtS97EE9lmHAqdPYbprZiY005byEwQh0S4vzsXbcE11fMwnAvPGskr3EQvYI623WLv4/nJgif1G1lGgvb5p0ilGjmL24Y3w4SyZqhkFpJH3oonROsHpbFowveVFTv3omnSIjkDw54C3JepiPIktyDdm24cYZP4PkRDuiW9u0tmpTn8S0BvT099WCSb9eehcsSWT5Ml629cxnUszaphpN8+l6n0dDswZ3GSlrTwI9r3n/x+jA92COxCde2/ILKbuEtksy3V6eKdbHu5V24bDZ65n/jV3ZoFy8S3lgcOcyyNLBreVulKQWhOJ1I5KByuC5hkDsrkSGsVMXOfb/5vE0aibozjs9fzUnwjOD3iaYZe+0xdUl1viKFl/Xq4swez9vWmTw4wPYmM+qsOXjaZiqxXKFRn4KovyLWEYWGlFzYH3i8RqBON8J/ccvSRT7RKN+4ZUVVdKfq2qF/a002u7A0UHiZURgtTngxMAWtQ5Xz851Er+P0TA137voBrChv7SYTh9lejqw/45eZrBdGKCRhUq3qcoIJLiT09uIh9tkUO4KUfkiXd8lZLZ4MZc=
  skip_cleanup: true
  on:
    branch: master
    tags: true
